import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {SidebarProvider, SidebarTrigger, SidebarInset} from "@/components/ui/sidebar"
import {AppSidebar} from "@/app/components/sidebar"
import { TooltipProvider } from "@/components/ui/tooltip";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} ${geistSans.variable} font-sans`}>
        <TooltipProvider>
          <SidebarProvider>
            <AppSidebar />

            <SidebarInset className="min-h-screen">
              <SidebarTrigger className="cursor-pointer" />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}